name: Waka Readme

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_TIMEZONE: true
          SHOW_EDITORS: false
          SHOW_PROJECTS: false
          SHOW_LANGUAGE: true
          SHOW_OS: false
          SHOW_COMMIT: false
          SHOW_PROFILE_VIEWS: false
          SHOW_LOC_CHART: false
          LOCALE: "en"

      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: waka-projects
          SHOW_TITLE: false
          SHOW_TIME: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_TIMEZONE: false
          SHOW_EDITORS: false
          SHOW_PROJECTS: true
          SHOW_LANGUAGE: false
          SHOW_OS: false
          SHOW_COMMIT: true
          SHOW_PROFILE_VIEWS: false
          SHOW_LOC_CHART: false
          LOCALE: "en"
          COMMIT_MESSAGE: "ðŸ“Š Updated development metrics"
